[package]
name = "tee-rs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/pollenjp/tee-rs"

[dependencies]
libc = "0.2.161"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
